[tool.poetry]
name = "nonebot-plugin-wenxin"
version = "0.1.0"
description = "文心一言 Nonebot 插件"
authors = ["Noctulus <fangyuhao0612@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "nonebot_plugin_wenxin/*.py"}
]

[tool.poetry.dependencies]
python = "^3.10"
nonebot2 = "^2.0.0-beta.1"
aiohttp = "^3.8.5"
requests = "^2.31.0"
nonebot-plugin-apscheduler = "^0.3.0"
nonebot-adapter-onebot = "^2.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
